### ISSUE TITLE
implementation of your app

### ISSUE THREAD

**Issue by echopros** [deepak786/InstagramLikeColorTransition#1]
hi how are you. thanks for this useful app, 
it will be a favour if yous show us how to implement your app in our ready apps, that contain an existing simple background. 
i¡m beginner 
thanks in advance

**Comment by deepak786** [comment]
Hi,
I already have a gist which explains how to use this transition animation.
Please check the gist at https://gist.github.com/deepak786/12eee8412fa7914a16774ce546e1a089
Hope this helps you.

**Comment by echopros** [comment]
Great brother. Thank you. I will try once i’m at home.

**Comment by echopros** [comment]
Great tutorial. Done. Thank you man 😁😁😁🙏🙏🙏🙏🙏

**Comment by Aniket204** [comment]
When i set this as background on a static screen with little imageview and textviews it crashes
